hardware:
  A100:
    cost_per_hour: 0.68493
  L4:
    cost_per_hour: 0.6
  H200:
    cost_per_hour: 0.68493

token_rates:
  ChatGPT:
    A100:
      prefill: 12567
      decode: 12567
    L4:
      prefill: 12567
      decode: 12567
  GPT-4:
    A100:
      prefill: 12567
      decode: 12567
    L4:
      prefill: 12567
      decode: 12567

api_providers:
  OpenAI:
    latency: 0.5
    cost_input:
      ChatGPT: 0.0000002
      GPT-4: 0.0000002
    cost_output:
      ChatGPT: 0.0000008
      GPT-4: 0.0000008
  Anthropic:
    latency: 0.7
    cost_input:
      Claude-3: 0.00001
    cost_output:
      Claude-3: 0.00002
